macro_rules! glorp_calls {
	($macro:ident) => {
		$macro! {
			Txn {
				id: "txn",
				docs: "Apply multiple mutation calls atomically.",
				kind: Mutation,
				route: Runtime,
				transactional: false,
				input: some(crate::GlorpTxn),
				output: crate::GlorpOutcome,
			},
			ConfigSet {
				id: "config-set",
				docs: "Set one config field.",
				kind: Mutation,
				route: Runtime,
				transactional: true,
				input: some(crate::ConfigAssignment),
				output: crate::GlorpOutcome,
			},
			ConfigReset {
				id: "config-reset",
				docs: "Reset one config field to its default.",
				kind: Mutation,
				route: Runtime,
				transactional: true,
				input: some(crate::ConfigPathInput),
				output: crate::GlorpOutcome,
			},
			ConfigPatch {
				id: "config-patch",
				docs: "Patch config with a record.",
				kind: Mutation,
				route: Runtime,
				transactional: true,
				input: some(crate::ConfigPatchInput),
				output: crate::GlorpOutcome,
			},
			ConfigReload {
				id: "config-reload",
				docs: "Reload the durable config file.",
				kind: Mutation,
				route: Runtime,
				transactional: true,
				input: none,
				output: crate::GlorpOutcome,
			},
			ConfigPersist {
				id: "config-persist",
				docs: "Persist the effective config file.",
				kind: Mutation,
				route: Runtime,
				transactional: true,
				input: none,
				output: crate::GlorpOutcome,
			},
			DocumentReplace {
				id: "document-replace",
				docs: "Replace the document text.",
				kind: Mutation,
				route: Runtime,
				transactional: true,
				input: some(crate::TextInput),
				output: crate::GlorpOutcome,
			},
			EditorMotion {
				id: "editor-motion",
				docs: "Apply a typed editor motion.",
				kind: Mutation,
				route: Runtime,
				transactional: true,
				input: some(crate::EditorMotionInput),
				output: crate::GlorpOutcome,
			},
			EditorMode {
				id: "editor-mode",
				docs: "Apply a typed editor mode change.",
				kind: Mutation,
				route: Runtime,
				transactional: true,
				input: some(crate::EditorModeInput),
				output: crate::GlorpOutcome,
			},
			EditorInsert {
				id: "editor-insert",
				docs: "Insert text at the current selection.",
				kind: Mutation,
				route: Runtime,
				transactional: true,
				input: some(crate::TextInput),
				output: crate::GlorpOutcome,
			},
			EditorBackspace {
				id: "editor-backspace",
				docs: "Delete backward.",
				kind: Mutation,
				route: Runtime,
				transactional: true,
				input: none,
				output: crate::GlorpOutcome,
			},
			EditorDeleteForward {
				id: "editor-delete-forward",
				docs: "Delete forward.",
				kind: Mutation,
				route: Runtime,
				transactional: true,
				input: none,
				output: crate::GlorpOutcome,
			},
			EditorDeleteSelection {
				id: "editor-delete-selection",
				docs: "Delete the current selection.",
				kind: Mutation,
				route: Runtime,
				transactional: true,
				input: none,
				output: crate::GlorpOutcome,
			},
			EditorHistory {
				id: "editor-history",
				docs: "Apply editor history navigation.",
				kind: Mutation,
				route: Runtime,
				transactional: true,
				input: some(crate::EditorHistoryInput),
				output: crate::GlorpOutcome,
			},
			Schema {
				id: "schema",
				docs: "Return the protocol reflection schema.",
				kind: Read,
				route: Runtime,
				transactional: false,
				input: none,
				output: crate::GlorpSchema,
			},
			Config {
				id: "config",
				docs: "Return the effective runtime config.",
				kind: Read,
				route: Runtime,
				transactional: false,
				input: none,
				output: crate::GlorpConfig,
			},
			DocumentText {
				id: "document-text",
				docs: "Return the current document text.",
				kind: Read,
				route: Runtime,
				transactional: false,
				input: none,
				output: String,
			},
			Editor {
				id: "editor",
				docs: "Return the current editor read model.",
				kind: Read,
				route: Runtime,
				transactional: false,
				input: none,
				output: crate::EditorStateView,
			},
			Capabilities {
				id: "capabilities",
				docs: "Return stable runtime capability flags.",
				kind: Read,
				route: Runtime,
				transactional: false,
				input: none,
				output: crate::GlorpCapabilities,
			},
			SessionAttach {
				id: "session-attach",
				docs: "Resolve and validate a live Glorp session.",
				kind: Helper,
				route: Client,
				transactional: false,
				input: none,
				output: crate::GlorpSessionView,
			},
			SessionShutdown {
				id: "session-shutdown",
				docs: "Stop the live shared runtime for the resolved session.",
				kind: Helper,
				route: Transport,
				transactional: false,
				input: none,
				output: crate::OkView,
			},
			ConfigValidate {
				id: "config-validate",
				docs: "Validate a config value without mutating runtime state.",
				kind: Helper,
				route: Client,
				transactional: false,
				input: some(crate::ConfigAssignment),
				output: crate::OkView,
			},
			EventsSubscribe {
				id: "events-subscribe",
				docs: "Subscribe to runtime change events.",
				kind: Helper,
				route: Runtime,
				transactional: false,
				input: none,
				output: crate::GlorpEventStreamView,
			},
			EventsNext {
				id: "events-next",
				docs: "Poll the next event for a subscription token.",
				kind: Helper,
				route: Runtime,
				transactional: false,
				input: some(crate::StreamTokenInput),
				output: Option<crate::GlorpEvent>,
			},
			EventsUnsubscribe {
				id: "events-unsubscribe",
				docs: "Release a subscription token.",
				kind: Helper,
				route: Runtime,
				transactional: false,
				input: some(crate::StreamTokenInput),
				output: crate::TokenAckView,
			},
		}
	};
}

pub(crate) use glorp_calls;
