// Generated by `cargo run -p glorp_api_codegen`. Do not edit by hand.
use {super::*, std::sync::LazyLock};

static CALL_SPECS: LazyLock<Vec<GlorpCallSpec>> = LazyLock::new(|| {
	let specs = vec![
		GlorpCallSpec {
			id: "txn".to_owned(),
			kind: GlorpCallKind::Mutation,
			route: GlorpCallRoute::Runtime,
			docs: "Apply multiple mutation calls atomically.".to_owned(),
			input: Some(named::<crate::GlorpTxn>()),
			output: named::<crate::GlorpOutcome>(),
			transactional: false,
		},
		GlorpCallSpec {
			id: "config-set".to_owned(),
			kind: GlorpCallKind::Mutation,
			route: GlorpCallRoute::Runtime,
			docs: "Set one config field.".to_owned(),
			input: Some(named::<crate::ConfigAssignment>()),
			output: named::<crate::GlorpOutcome>(),
			transactional: true,
		},
		GlorpCallSpec {
			id: "config-reset".to_owned(),
			kind: GlorpCallKind::Mutation,
			route: GlorpCallRoute::Runtime,
			docs: "Reset one config field to its default.".to_owned(),
			input: Some(named::<crate::ConfigPathInput>()),
			output: named::<crate::GlorpOutcome>(),
			transactional: true,
		},
		GlorpCallSpec {
			id: "config-patch".to_owned(),
			kind: GlorpCallKind::Mutation,
			route: GlorpCallRoute::Runtime,
			docs: "Patch config with a record.".to_owned(),
			input: Some(named::<crate::ConfigPatchInput>()),
			output: named::<crate::GlorpOutcome>(),
			transactional: true,
		},
		GlorpCallSpec {
			id: "config-reload".to_owned(),
			kind: GlorpCallKind::Mutation,
			route: GlorpCallRoute::Runtime,
			docs: "Reload the durable config file.".to_owned(),
			input: None,
			output: named::<crate::GlorpOutcome>(),
			transactional: true,
		},
		GlorpCallSpec {
			id: "config-persist".to_owned(),
			kind: GlorpCallKind::Mutation,
			route: GlorpCallRoute::Runtime,
			docs: "Persist the effective config file.".to_owned(),
			input: None,
			output: named::<crate::GlorpOutcome>(),
			transactional: true,
		},
		GlorpCallSpec {
			id: "document-replace".to_owned(),
			kind: GlorpCallKind::Mutation,
			route: GlorpCallRoute::Runtime,
			docs: "Replace the document text.".to_owned(),
			input: Some(named::<crate::TextInput>()),
			output: named::<crate::GlorpOutcome>(),
			transactional: true,
		},
		GlorpCallSpec {
			id: "editor-motion".to_owned(),
			kind: GlorpCallKind::Mutation,
			route: GlorpCallRoute::Runtime,
			docs: "Apply a typed editor motion.".to_owned(),
			input: Some(named::<crate::EditorMotionInput>()),
			output: named::<crate::GlorpOutcome>(),
			transactional: true,
		},
		GlorpCallSpec {
			id: "editor-mode".to_owned(),
			kind: GlorpCallKind::Mutation,
			route: GlorpCallRoute::Runtime,
			docs: "Apply a typed editor mode change.".to_owned(),
			input: Some(named::<crate::EditorModeInput>()),
			output: named::<crate::GlorpOutcome>(),
			transactional: true,
		},
		GlorpCallSpec {
			id: "editor-insert".to_owned(),
			kind: GlorpCallKind::Mutation,
			route: GlorpCallRoute::Runtime,
			docs: "Insert text at the current selection.".to_owned(),
			input: Some(named::<crate::TextInput>()),
			output: named::<crate::GlorpOutcome>(),
			transactional: true,
		},
		GlorpCallSpec {
			id: "editor-backspace".to_owned(),
			kind: GlorpCallKind::Mutation,
			route: GlorpCallRoute::Runtime,
			docs: "Delete backward.".to_owned(),
			input: None,
			output: named::<crate::GlorpOutcome>(),
			transactional: true,
		},
		GlorpCallSpec {
			id: "editor-delete-forward".to_owned(),
			kind: GlorpCallKind::Mutation,
			route: GlorpCallRoute::Runtime,
			docs: "Delete forward.".to_owned(),
			input: None,
			output: named::<crate::GlorpOutcome>(),
			transactional: true,
		},
		GlorpCallSpec {
			id: "editor-delete-selection".to_owned(),
			kind: GlorpCallKind::Mutation,
			route: GlorpCallRoute::Runtime,
			docs: "Delete the current selection.".to_owned(),
			input: None,
			output: named::<crate::GlorpOutcome>(),
			transactional: true,
		},
		GlorpCallSpec {
			id: "editor-history".to_owned(),
			kind: GlorpCallKind::Mutation,
			route: GlorpCallRoute::Runtime,
			docs: "Apply editor history navigation.".to_owned(),
			input: Some(named::<crate::EditorHistoryInput>()),
			output: named::<crate::GlorpOutcome>(),
			transactional: true,
		},
		GlorpCallSpec {
			id: "schema".to_owned(),
			kind: GlorpCallKind::Read,
			route: GlorpCallRoute::Runtime,
			docs: "Return the protocol reflection schema.".to_owned(),
			input: None,
			output: named::<crate::GlorpSchema>(),
			transactional: false,
		},
		GlorpCallSpec {
			id: "config".to_owned(),
			kind: GlorpCallKind::Read,
			route: GlorpCallRoute::Runtime,
			docs: "Return the effective runtime config.".to_owned(),
			input: None,
			output: named::<crate::GlorpConfig>(),
			transactional: false,
		},
		GlorpCallSpec {
			id: "document-text".to_owned(),
			kind: GlorpCallKind::Read,
			route: GlorpCallRoute::Runtime,
			docs: "Return the current document text.".to_owned(),
			input: None,
			output: named::<String>(),
			transactional: false,
		},
		GlorpCallSpec {
			id: "editor".to_owned(),
			kind: GlorpCallKind::Read,
			route: GlorpCallRoute::Runtime,
			docs: "Return the current editor read model.".to_owned(),
			input: None,
			output: named::<crate::EditorStateView>(),
			transactional: false,
		},
		GlorpCallSpec {
			id: "capabilities".to_owned(),
			kind: GlorpCallKind::Read,
			route: GlorpCallRoute::Runtime,
			docs: "Return stable runtime capability flags.".to_owned(),
			input: None,
			output: named::<crate::GlorpCapabilities>(),
			transactional: false,
		},
		GlorpCallSpec {
			id: "session-attach".to_owned(),
			kind: GlorpCallKind::Helper,
			route: GlorpCallRoute::Client,
			docs: "Resolve and validate a live Glorp session.".to_owned(),
			input: None,
			output: named::<crate::GlorpSessionView>(),
			transactional: false,
		},
		GlorpCallSpec {
			id: "session-shutdown".to_owned(),
			kind: GlorpCallKind::Helper,
			route: GlorpCallRoute::Transport,
			docs: "Stop the live shared runtime for the resolved session.".to_owned(),
			input: None,
			output: named::<crate::OkView>(),
			transactional: false,
		},
		GlorpCallSpec {
			id: "config-validate".to_owned(),
			kind: GlorpCallKind::Helper,
			route: GlorpCallRoute::Client,
			docs: "Validate a config value without mutating runtime state.".to_owned(),
			input: Some(named::<crate::ConfigAssignment>()),
			output: named::<crate::OkView>(),
			transactional: false,
		},
		GlorpCallSpec {
			id: "events-subscribe".to_owned(),
			kind: GlorpCallKind::Helper,
			route: GlorpCallRoute::Runtime,
			docs: "Subscribe to runtime change events.".to_owned(),
			input: None,
			output: named::<crate::GlorpEventStreamView>(),
			transactional: false,
		},
		GlorpCallSpec {
			id: "events-next".to_owned(),
			kind: GlorpCallKind::Helper,
			route: GlorpCallRoute::Runtime,
			docs: "Poll the next event for a subscription token.".to_owned(),
			input: Some(named::<crate::StreamTokenInput>()),
			output: named::<Option<crate::GlorpEvent>>(),
			transactional: false,
		},
		GlorpCallSpec {
			id: "events-unsubscribe".to_owned(),
			kind: GlorpCallKind::Helper,
			route: GlorpCallRoute::Runtime,
			docs: "Release a subscription token.".to_owned(),
			input: Some(named::<crate::StreamTokenInput>()),
			output: named::<crate::TokenAckView>(),
			transactional: false,
		},
	];
	debug_assert_catalog_invariants(&specs);
	specs
});

pub mod calls {
	use super::*;

	#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
	pub struct Txn;

	impl GlorpCallDescriptor for Txn {
		type Input = crate::GlorpTxn;
		type Output = crate::GlorpOutcome;

		const ID: &'static str = "txn";
		const DOCS: &'static str = "Apply multiple mutation calls atomically.";
		const KIND: GlorpCallKind = GlorpCallKind::Mutation;
		const ROUTE: GlorpCallRoute = GlorpCallRoute::Runtime;
		const TRANSACTIONAL: bool = false;

		fn input_type() -> Option<TypeRef> {
			Some(named::<crate::GlorpTxn>())
		}

		fn output_type() -> TypeRef {
			named::<crate::GlorpOutcome>()
		}

		fn build(input: Self::Input) -> Result<GlorpCall, GlorpError> {
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: Some(encode_value(Self::ID, "input", input)?),
			})
		}

		fn build_raw(input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {
			let input = decode_required::<crate::GlorpTxn>(Self::ID, "input", input)?;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: Some(encode_value(Self::ID, "input", input)?),
			})
		}

		fn decode_call_input(call: &GlorpCall) -> Result<Self::Input, GlorpError> {
			ensure_call_id(Self::ID, &call.id)?;
			decode_required::<crate::GlorpTxn>(Self::ID, "input", call.input.as_ref())
		}
	}

	#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
	pub struct ConfigSet;

	impl GlorpCallDescriptor for ConfigSet {
		type Input = crate::ConfigAssignment;
		type Output = crate::GlorpOutcome;

		const ID: &'static str = "config-set";
		const DOCS: &'static str = "Set one config field.";
		const KIND: GlorpCallKind = GlorpCallKind::Mutation;
		const ROUTE: GlorpCallRoute = GlorpCallRoute::Runtime;
		const TRANSACTIONAL: bool = true;

		fn input_type() -> Option<TypeRef> {
			Some(named::<crate::ConfigAssignment>())
		}

		fn output_type() -> TypeRef {
			named::<crate::GlorpOutcome>()
		}

		fn build(input: Self::Input) -> Result<GlorpCall, GlorpError> {
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: Some(encode_value(Self::ID, "input", input)?),
			})
		}

		fn build_raw(input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {
			let input = decode_required::<crate::ConfigAssignment>(Self::ID, "input", input)?;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: Some(encode_value(Self::ID, "input", input)?),
			})
		}

		fn decode_call_input(call: &GlorpCall) -> Result<Self::Input, GlorpError> {
			ensure_call_id(Self::ID, &call.id)?;
			decode_required::<crate::ConfigAssignment>(Self::ID, "input", call.input.as_ref())
		}
	}

	#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
	pub struct ConfigReset;

	impl GlorpCallDescriptor for ConfigReset {
		type Input = crate::ConfigPathInput;
		type Output = crate::GlorpOutcome;

		const ID: &'static str = "config-reset";
		const DOCS: &'static str = "Reset one config field to its default.";
		const KIND: GlorpCallKind = GlorpCallKind::Mutation;
		const ROUTE: GlorpCallRoute = GlorpCallRoute::Runtime;
		const TRANSACTIONAL: bool = true;

		fn input_type() -> Option<TypeRef> {
			Some(named::<crate::ConfigPathInput>())
		}

		fn output_type() -> TypeRef {
			named::<crate::GlorpOutcome>()
		}

		fn build(input: Self::Input) -> Result<GlorpCall, GlorpError> {
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: Some(encode_value(Self::ID, "input", input)?),
			})
		}

		fn build_raw(input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {
			let input = decode_required::<crate::ConfigPathInput>(Self::ID, "input", input)?;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: Some(encode_value(Self::ID, "input", input)?),
			})
		}

		fn decode_call_input(call: &GlorpCall) -> Result<Self::Input, GlorpError> {
			ensure_call_id(Self::ID, &call.id)?;
			decode_required::<crate::ConfigPathInput>(Self::ID, "input", call.input.as_ref())
		}
	}

	#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
	pub struct ConfigPatch;

	impl GlorpCallDescriptor for ConfigPatch {
		type Input = crate::ConfigPatchInput;
		type Output = crate::GlorpOutcome;

		const ID: &'static str = "config-patch";
		const DOCS: &'static str = "Patch config with a record.";
		const KIND: GlorpCallKind = GlorpCallKind::Mutation;
		const ROUTE: GlorpCallRoute = GlorpCallRoute::Runtime;
		const TRANSACTIONAL: bool = true;

		fn input_type() -> Option<TypeRef> {
			Some(named::<crate::ConfigPatchInput>())
		}

		fn output_type() -> TypeRef {
			named::<crate::GlorpOutcome>()
		}

		fn build(input: Self::Input) -> Result<GlorpCall, GlorpError> {
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: Some(encode_value(Self::ID, "input", input)?),
			})
		}

		fn build_raw(input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {
			let input = decode_required::<crate::ConfigPatchInput>(Self::ID, "input", input)?;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: Some(encode_value(Self::ID, "input", input)?),
			})
		}

		fn decode_call_input(call: &GlorpCall) -> Result<Self::Input, GlorpError> {
			ensure_call_id(Self::ID, &call.id)?;
			decode_required::<crate::ConfigPatchInput>(Self::ID, "input", call.input.as_ref())
		}
	}

	#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
	pub struct ConfigReload;

	impl GlorpCallDescriptor for ConfigReload {
		type Input = ();
		type Output = crate::GlorpOutcome;

		const ID: &'static str = "config-reload";
		const DOCS: &'static str = "Reload the durable config file.";
		const KIND: GlorpCallKind = GlorpCallKind::Mutation;
		const ROUTE: GlorpCallRoute = GlorpCallRoute::Runtime;
		const TRANSACTIONAL: bool = true;

		fn input_type() -> Option<TypeRef> {
			None
		}

		fn output_type() -> TypeRef {
			named::<crate::GlorpOutcome>()
		}

		fn build(input: Self::Input) -> Result<GlorpCall, GlorpError> {
			let _ = input;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: None,
			})
		}

		fn build_raw(input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {
			ensure_no_input(Self::ID, input)?;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: None,
			})
		}

		fn decode_call_input(call: &GlorpCall) -> Result<Self::Input, GlorpError> {
			ensure_call_id(Self::ID, &call.id)?;
			ensure_no_input(Self::ID, call.input.as_ref())?;
			Ok(())
		}
	}

	#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
	pub struct ConfigPersist;

	impl GlorpCallDescriptor for ConfigPersist {
		type Input = ();
		type Output = crate::GlorpOutcome;

		const ID: &'static str = "config-persist";
		const DOCS: &'static str = "Persist the effective config file.";
		const KIND: GlorpCallKind = GlorpCallKind::Mutation;
		const ROUTE: GlorpCallRoute = GlorpCallRoute::Runtime;
		const TRANSACTIONAL: bool = true;

		fn input_type() -> Option<TypeRef> {
			None
		}

		fn output_type() -> TypeRef {
			named::<crate::GlorpOutcome>()
		}

		fn build(input: Self::Input) -> Result<GlorpCall, GlorpError> {
			let _ = input;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: None,
			})
		}

		fn build_raw(input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {
			ensure_no_input(Self::ID, input)?;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: None,
			})
		}

		fn decode_call_input(call: &GlorpCall) -> Result<Self::Input, GlorpError> {
			ensure_call_id(Self::ID, &call.id)?;
			ensure_no_input(Self::ID, call.input.as_ref())?;
			Ok(())
		}
	}

	#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
	pub struct DocumentReplace;

	impl GlorpCallDescriptor for DocumentReplace {
		type Input = crate::TextInput;
		type Output = crate::GlorpOutcome;

		const ID: &'static str = "document-replace";
		const DOCS: &'static str = "Replace the document text.";
		const KIND: GlorpCallKind = GlorpCallKind::Mutation;
		const ROUTE: GlorpCallRoute = GlorpCallRoute::Runtime;
		const TRANSACTIONAL: bool = true;

		fn input_type() -> Option<TypeRef> {
			Some(named::<crate::TextInput>())
		}

		fn output_type() -> TypeRef {
			named::<crate::GlorpOutcome>()
		}

		fn build(input: Self::Input) -> Result<GlorpCall, GlorpError> {
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: Some(encode_value(Self::ID, "input", input)?),
			})
		}

		fn build_raw(input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {
			let input = decode_required::<crate::TextInput>(Self::ID, "input", input)?;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: Some(encode_value(Self::ID, "input", input)?),
			})
		}

		fn decode_call_input(call: &GlorpCall) -> Result<Self::Input, GlorpError> {
			ensure_call_id(Self::ID, &call.id)?;
			decode_required::<crate::TextInput>(Self::ID, "input", call.input.as_ref())
		}
	}

	#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
	pub struct EditorMotion;

	impl GlorpCallDescriptor for EditorMotion {
		type Input = crate::EditorMotionInput;
		type Output = crate::GlorpOutcome;

		const ID: &'static str = "editor-motion";
		const DOCS: &'static str = "Apply a typed editor motion.";
		const KIND: GlorpCallKind = GlorpCallKind::Mutation;
		const ROUTE: GlorpCallRoute = GlorpCallRoute::Runtime;
		const TRANSACTIONAL: bool = true;

		fn input_type() -> Option<TypeRef> {
			Some(named::<crate::EditorMotionInput>())
		}

		fn output_type() -> TypeRef {
			named::<crate::GlorpOutcome>()
		}

		fn build(input: Self::Input) -> Result<GlorpCall, GlorpError> {
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: Some(encode_value(Self::ID, "input", input)?),
			})
		}

		fn build_raw(input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {
			let input = decode_required::<crate::EditorMotionInput>(Self::ID, "input", input)?;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: Some(encode_value(Self::ID, "input", input)?),
			})
		}

		fn decode_call_input(call: &GlorpCall) -> Result<Self::Input, GlorpError> {
			ensure_call_id(Self::ID, &call.id)?;
			decode_required::<crate::EditorMotionInput>(Self::ID, "input", call.input.as_ref())
		}
	}

	#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
	pub struct EditorMode;

	impl GlorpCallDescriptor for EditorMode {
		type Input = crate::EditorModeInput;
		type Output = crate::GlorpOutcome;

		const ID: &'static str = "editor-mode";
		const DOCS: &'static str = "Apply a typed editor mode change.";
		const KIND: GlorpCallKind = GlorpCallKind::Mutation;
		const ROUTE: GlorpCallRoute = GlorpCallRoute::Runtime;
		const TRANSACTIONAL: bool = true;

		fn input_type() -> Option<TypeRef> {
			Some(named::<crate::EditorModeInput>())
		}

		fn output_type() -> TypeRef {
			named::<crate::GlorpOutcome>()
		}

		fn build(input: Self::Input) -> Result<GlorpCall, GlorpError> {
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: Some(encode_value(Self::ID, "input", input)?),
			})
		}

		fn build_raw(input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {
			let input = decode_required::<crate::EditorModeInput>(Self::ID, "input", input)?;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: Some(encode_value(Self::ID, "input", input)?),
			})
		}

		fn decode_call_input(call: &GlorpCall) -> Result<Self::Input, GlorpError> {
			ensure_call_id(Self::ID, &call.id)?;
			decode_required::<crate::EditorModeInput>(Self::ID, "input", call.input.as_ref())
		}
	}

	#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
	pub struct EditorInsert;

	impl GlorpCallDescriptor for EditorInsert {
		type Input = crate::TextInput;
		type Output = crate::GlorpOutcome;

		const ID: &'static str = "editor-insert";
		const DOCS: &'static str = "Insert text at the current selection.";
		const KIND: GlorpCallKind = GlorpCallKind::Mutation;
		const ROUTE: GlorpCallRoute = GlorpCallRoute::Runtime;
		const TRANSACTIONAL: bool = true;

		fn input_type() -> Option<TypeRef> {
			Some(named::<crate::TextInput>())
		}

		fn output_type() -> TypeRef {
			named::<crate::GlorpOutcome>()
		}

		fn build(input: Self::Input) -> Result<GlorpCall, GlorpError> {
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: Some(encode_value(Self::ID, "input", input)?),
			})
		}

		fn build_raw(input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {
			let input = decode_required::<crate::TextInput>(Self::ID, "input", input)?;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: Some(encode_value(Self::ID, "input", input)?),
			})
		}

		fn decode_call_input(call: &GlorpCall) -> Result<Self::Input, GlorpError> {
			ensure_call_id(Self::ID, &call.id)?;
			decode_required::<crate::TextInput>(Self::ID, "input", call.input.as_ref())
		}
	}

	#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
	pub struct EditorBackspace;

	impl GlorpCallDescriptor for EditorBackspace {
		type Input = ();
		type Output = crate::GlorpOutcome;

		const ID: &'static str = "editor-backspace";
		const DOCS: &'static str = "Delete backward.";
		const KIND: GlorpCallKind = GlorpCallKind::Mutation;
		const ROUTE: GlorpCallRoute = GlorpCallRoute::Runtime;
		const TRANSACTIONAL: bool = true;

		fn input_type() -> Option<TypeRef> {
			None
		}

		fn output_type() -> TypeRef {
			named::<crate::GlorpOutcome>()
		}

		fn build(input: Self::Input) -> Result<GlorpCall, GlorpError> {
			let _ = input;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: None,
			})
		}

		fn build_raw(input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {
			ensure_no_input(Self::ID, input)?;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: None,
			})
		}

		fn decode_call_input(call: &GlorpCall) -> Result<Self::Input, GlorpError> {
			ensure_call_id(Self::ID, &call.id)?;
			ensure_no_input(Self::ID, call.input.as_ref())?;
			Ok(())
		}
	}

	#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
	pub struct EditorDeleteForward;

	impl GlorpCallDescriptor for EditorDeleteForward {
		type Input = ();
		type Output = crate::GlorpOutcome;

		const ID: &'static str = "editor-delete-forward";
		const DOCS: &'static str = "Delete forward.";
		const KIND: GlorpCallKind = GlorpCallKind::Mutation;
		const ROUTE: GlorpCallRoute = GlorpCallRoute::Runtime;
		const TRANSACTIONAL: bool = true;

		fn input_type() -> Option<TypeRef> {
			None
		}

		fn output_type() -> TypeRef {
			named::<crate::GlorpOutcome>()
		}

		fn build(input: Self::Input) -> Result<GlorpCall, GlorpError> {
			let _ = input;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: None,
			})
		}

		fn build_raw(input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {
			ensure_no_input(Self::ID, input)?;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: None,
			})
		}

		fn decode_call_input(call: &GlorpCall) -> Result<Self::Input, GlorpError> {
			ensure_call_id(Self::ID, &call.id)?;
			ensure_no_input(Self::ID, call.input.as_ref())?;
			Ok(())
		}
	}

	#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
	pub struct EditorDeleteSelection;

	impl GlorpCallDescriptor for EditorDeleteSelection {
		type Input = ();
		type Output = crate::GlorpOutcome;

		const ID: &'static str = "editor-delete-selection";
		const DOCS: &'static str = "Delete the current selection.";
		const KIND: GlorpCallKind = GlorpCallKind::Mutation;
		const ROUTE: GlorpCallRoute = GlorpCallRoute::Runtime;
		const TRANSACTIONAL: bool = true;

		fn input_type() -> Option<TypeRef> {
			None
		}

		fn output_type() -> TypeRef {
			named::<crate::GlorpOutcome>()
		}

		fn build(input: Self::Input) -> Result<GlorpCall, GlorpError> {
			let _ = input;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: None,
			})
		}

		fn build_raw(input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {
			ensure_no_input(Self::ID, input)?;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: None,
			})
		}

		fn decode_call_input(call: &GlorpCall) -> Result<Self::Input, GlorpError> {
			ensure_call_id(Self::ID, &call.id)?;
			ensure_no_input(Self::ID, call.input.as_ref())?;
			Ok(())
		}
	}

	#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
	pub struct EditorHistory;

	impl GlorpCallDescriptor for EditorHistory {
		type Input = crate::EditorHistoryInput;
		type Output = crate::GlorpOutcome;

		const ID: &'static str = "editor-history";
		const DOCS: &'static str = "Apply editor history navigation.";
		const KIND: GlorpCallKind = GlorpCallKind::Mutation;
		const ROUTE: GlorpCallRoute = GlorpCallRoute::Runtime;
		const TRANSACTIONAL: bool = true;

		fn input_type() -> Option<TypeRef> {
			Some(named::<crate::EditorHistoryInput>())
		}

		fn output_type() -> TypeRef {
			named::<crate::GlorpOutcome>()
		}

		fn build(input: Self::Input) -> Result<GlorpCall, GlorpError> {
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: Some(encode_value(Self::ID, "input", input)?),
			})
		}

		fn build_raw(input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {
			let input = decode_required::<crate::EditorHistoryInput>(Self::ID, "input", input)?;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: Some(encode_value(Self::ID, "input", input)?),
			})
		}

		fn decode_call_input(call: &GlorpCall) -> Result<Self::Input, GlorpError> {
			ensure_call_id(Self::ID, &call.id)?;
			decode_required::<crate::EditorHistoryInput>(Self::ID, "input", call.input.as_ref())
		}
	}

	#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
	pub struct Schema;

	impl GlorpCallDescriptor for Schema {
		type Input = ();
		type Output = crate::GlorpSchema;

		const ID: &'static str = "schema";
		const DOCS: &'static str = "Return the protocol reflection schema.";
		const KIND: GlorpCallKind = GlorpCallKind::Read;
		const ROUTE: GlorpCallRoute = GlorpCallRoute::Runtime;
		const TRANSACTIONAL: bool = false;

		fn input_type() -> Option<TypeRef> {
			None
		}

		fn output_type() -> TypeRef {
			named::<crate::GlorpSchema>()
		}

		fn build(input: Self::Input) -> Result<GlorpCall, GlorpError> {
			let _ = input;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: None,
			})
		}

		fn build_raw(input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {
			ensure_no_input(Self::ID, input)?;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: None,
			})
		}

		fn decode_call_input(call: &GlorpCall) -> Result<Self::Input, GlorpError> {
			ensure_call_id(Self::ID, &call.id)?;
			ensure_no_input(Self::ID, call.input.as_ref())?;
			Ok(())
		}
	}

	#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
	pub struct Config;

	impl GlorpCallDescriptor for Config {
		type Input = ();
		type Output = crate::GlorpConfig;

		const ID: &'static str = "config";
		const DOCS: &'static str = "Return the effective runtime config.";
		const KIND: GlorpCallKind = GlorpCallKind::Read;
		const ROUTE: GlorpCallRoute = GlorpCallRoute::Runtime;
		const TRANSACTIONAL: bool = false;

		fn input_type() -> Option<TypeRef> {
			None
		}

		fn output_type() -> TypeRef {
			named::<crate::GlorpConfig>()
		}

		fn build(input: Self::Input) -> Result<GlorpCall, GlorpError> {
			let _ = input;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: None,
			})
		}

		fn build_raw(input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {
			ensure_no_input(Self::ID, input)?;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: None,
			})
		}

		fn decode_call_input(call: &GlorpCall) -> Result<Self::Input, GlorpError> {
			ensure_call_id(Self::ID, &call.id)?;
			ensure_no_input(Self::ID, call.input.as_ref())?;
			Ok(())
		}
	}

	#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
	pub struct DocumentText;

	impl GlorpCallDescriptor for DocumentText {
		type Input = ();
		type Output = String;

		const ID: &'static str = "document-text";
		const DOCS: &'static str = "Return the current document text.";
		const KIND: GlorpCallKind = GlorpCallKind::Read;
		const ROUTE: GlorpCallRoute = GlorpCallRoute::Runtime;
		const TRANSACTIONAL: bool = false;

		fn input_type() -> Option<TypeRef> {
			None
		}

		fn output_type() -> TypeRef {
			named::<String>()
		}

		fn build(input: Self::Input) -> Result<GlorpCall, GlorpError> {
			let _ = input;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: None,
			})
		}

		fn build_raw(input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {
			ensure_no_input(Self::ID, input)?;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: None,
			})
		}

		fn decode_call_input(call: &GlorpCall) -> Result<Self::Input, GlorpError> {
			ensure_call_id(Self::ID, &call.id)?;
			ensure_no_input(Self::ID, call.input.as_ref())?;
			Ok(())
		}
	}

	#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
	pub struct Editor;

	impl GlorpCallDescriptor for Editor {
		type Input = ();
		type Output = crate::EditorStateView;

		const ID: &'static str = "editor";
		const DOCS: &'static str = "Return the current editor read model.";
		const KIND: GlorpCallKind = GlorpCallKind::Read;
		const ROUTE: GlorpCallRoute = GlorpCallRoute::Runtime;
		const TRANSACTIONAL: bool = false;

		fn input_type() -> Option<TypeRef> {
			None
		}

		fn output_type() -> TypeRef {
			named::<crate::EditorStateView>()
		}

		fn build(input: Self::Input) -> Result<GlorpCall, GlorpError> {
			let _ = input;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: None,
			})
		}

		fn build_raw(input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {
			ensure_no_input(Self::ID, input)?;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: None,
			})
		}

		fn decode_call_input(call: &GlorpCall) -> Result<Self::Input, GlorpError> {
			ensure_call_id(Self::ID, &call.id)?;
			ensure_no_input(Self::ID, call.input.as_ref())?;
			Ok(())
		}
	}

	#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
	pub struct Capabilities;

	impl GlorpCallDescriptor for Capabilities {
		type Input = ();
		type Output = crate::GlorpCapabilities;

		const ID: &'static str = "capabilities";
		const DOCS: &'static str = "Return stable runtime capability flags.";
		const KIND: GlorpCallKind = GlorpCallKind::Read;
		const ROUTE: GlorpCallRoute = GlorpCallRoute::Runtime;
		const TRANSACTIONAL: bool = false;

		fn input_type() -> Option<TypeRef> {
			None
		}

		fn output_type() -> TypeRef {
			named::<crate::GlorpCapabilities>()
		}

		fn build(input: Self::Input) -> Result<GlorpCall, GlorpError> {
			let _ = input;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: None,
			})
		}

		fn build_raw(input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {
			ensure_no_input(Self::ID, input)?;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: None,
			})
		}

		fn decode_call_input(call: &GlorpCall) -> Result<Self::Input, GlorpError> {
			ensure_call_id(Self::ID, &call.id)?;
			ensure_no_input(Self::ID, call.input.as_ref())?;
			Ok(())
		}
	}

	#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
	pub struct SessionAttach;

	impl GlorpCallDescriptor for SessionAttach {
		type Input = ();
		type Output = crate::GlorpSessionView;

		const ID: &'static str = "session-attach";
		const DOCS: &'static str = "Resolve and validate a live Glorp session.";
		const KIND: GlorpCallKind = GlorpCallKind::Helper;
		const ROUTE: GlorpCallRoute = GlorpCallRoute::Client;
		const TRANSACTIONAL: bool = false;

		fn input_type() -> Option<TypeRef> {
			None
		}

		fn output_type() -> TypeRef {
			named::<crate::GlorpSessionView>()
		}

		fn build(input: Self::Input) -> Result<GlorpCall, GlorpError> {
			let _ = input;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: None,
			})
		}

		fn build_raw(input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {
			ensure_no_input(Self::ID, input)?;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: None,
			})
		}

		fn decode_call_input(call: &GlorpCall) -> Result<Self::Input, GlorpError> {
			ensure_call_id(Self::ID, &call.id)?;
			ensure_no_input(Self::ID, call.input.as_ref())?;
			Ok(())
		}
	}

	#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
	pub struct SessionShutdown;

	impl GlorpCallDescriptor for SessionShutdown {
		type Input = ();
		type Output = crate::OkView;

		const ID: &'static str = "session-shutdown";
		const DOCS: &'static str = "Stop the live shared runtime for the resolved session.";
		const KIND: GlorpCallKind = GlorpCallKind::Helper;
		const ROUTE: GlorpCallRoute = GlorpCallRoute::Transport;
		const TRANSACTIONAL: bool = false;

		fn input_type() -> Option<TypeRef> {
			None
		}

		fn output_type() -> TypeRef {
			named::<crate::OkView>()
		}

		fn build(input: Self::Input) -> Result<GlorpCall, GlorpError> {
			let _ = input;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: None,
			})
		}

		fn build_raw(input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {
			ensure_no_input(Self::ID, input)?;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: None,
			})
		}

		fn decode_call_input(call: &GlorpCall) -> Result<Self::Input, GlorpError> {
			ensure_call_id(Self::ID, &call.id)?;
			ensure_no_input(Self::ID, call.input.as_ref())?;
			Ok(())
		}
	}

	#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
	pub struct ConfigValidate;

	impl GlorpCallDescriptor for ConfigValidate {
		type Input = crate::ConfigAssignment;
		type Output = crate::OkView;

		const ID: &'static str = "config-validate";
		const DOCS: &'static str = "Validate a config value without mutating runtime state.";
		const KIND: GlorpCallKind = GlorpCallKind::Helper;
		const ROUTE: GlorpCallRoute = GlorpCallRoute::Client;
		const TRANSACTIONAL: bool = false;

		fn input_type() -> Option<TypeRef> {
			Some(named::<crate::ConfigAssignment>())
		}

		fn output_type() -> TypeRef {
			named::<crate::OkView>()
		}

		fn build(input: Self::Input) -> Result<GlorpCall, GlorpError> {
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: Some(encode_value(Self::ID, "input", input)?),
			})
		}

		fn build_raw(input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {
			let input = decode_required::<crate::ConfigAssignment>(Self::ID, "input", input)?;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: Some(encode_value(Self::ID, "input", input)?),
			})
		}

		fn decode_call_input(call: &GlorpCall) -> Result<Self::Input, GlorpError> {
			ensure_call_id(Self::ID, &call.id)?;
			decode_required::<crate::ConfigAssignment>(Self::ID, "input", call.input.as_ref())
		}
	}

	#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
	pub struct EventsSubscribe;

	impl GlorpCallDescriptor for EventsSubscribe {
		type Input = ();
		type Output = crate::GlorpEventStreamView;

		const ID: &'static str = "events-subscribe";
		const DOCS: &'static str = "Subscribe to runtime change events.";
		const KIND: GlorpCallKind = GlorpCallKind::Helper;
		const ROUTE: GlorpCallRoute = GlorpCallRoute::Runtime;
		const TRANSACTIONAL: bool = false;

		fn input_type() -> Option<TypeRef> {
			None
		}

		fn output_type() -> TypeRef {
			named::<crate::GlorpEventStreamView>()
		}

		fn build(input: Self::Input) -> Result<GlorpCall, GlorpError> {
			let _ = input;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: None,
			})
		}

		fn build_raw(input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {
			ensure_no_input(Self::ID, input)?;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: None,
			})
		}

		fn decode_call_input(call: &GlorpCall) -> Result<Self::Input, GlorpError> {
			ensure_call_id(Self::ID, &call.id)?;
			ensure_no_input(Self::ID, call.input.as_ref())?;
			Ok(())
		}
	}

	#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
	pub struct EventsNext;

	impl GlorpCallDescriptor for EventsNext {
		type Input = crate::StreamTokenInput;
		type Output = Option<crate::GlorpEvent>;

		const ID: &'static str = "events-next";
		const DOCS: &'static str = "Poll the next event for a subscription token.";
		const KIND: GlorpCallKind = GlorpCallKind::Helper;
		const ROUTE: GlorpCallRoute = GlorpCallRoute::Runtime;
		const TRANSACTIONAL: bool = false;

		fn input_type() -> Option<TypeRef> {
			Some(named::<crate::StreamTokenInput>())
		}

		fn output_type() -> TypeRef {
			named::<Option<crate::GlorpEvent>>()
		}

		fn build(input: Self::Input) -> Result<GlorpCall, GlorpError> {
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: Some(encode_value(Self::ID, "input", input)?),
			})
		}

		fn build_raw(input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {
			let input = decode_required::<crate::StreamTokenInput>(Self::ID, "input", input)?;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: Some(encode_value(Self::ID, "input", input)?),
			})
		}

		fn decode_call_input(call: &GlorpCall) -> Result<Self::Input, GlorpError> {
			ensure_call_id(Self::ID, &call.id)?;
			decode_required::<crate::StreamTokenInput>(Self::ID, "input", call.input.as_ref())
		}
	}

	#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
	pub struct EventsUnsubscribe;

	impl GlorpCallDescriptor for EventsUnsubscribe {
		type Input = crate::StreamTokenInput;
		type Output = crate::TokenAckView;

		const ID: &'static str = "events-unsubscribe";
		const DOCS: &'static str = "Release a subscription token.";
		const KIND: GlorpCallKind = GlorpCallKind::Helper;
		const ROUTE: GlorpCallRoute = GlorpCallRoute::Runtime;
		const TRANSACTIONAL: bool = false;

		fn input_type() -> Option<TypeRef> {
			Some(named::<crate::StreamTokenInput>())
		}

		fn output_type() -> TypeRef {
			named::<crate::TokenAckView>()
		}

		fn build(input: Self::Input) -> Result<GlorpCall, GlorpError> {
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: Some(encode_value(Self::ID, "input", input)?),
			})
		}

		fn build_raw(input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {
			let input = decode_required::<crate::StreamTokenInput>(Self::ID, "input", input)?;
			Ok(GlorpCall {
				id: Self::ID.to_owned(),
				input: Some(encode_value(Self::ID, "input", input)?),
			})
		}

		fn decode_call_input(call: &GlorpCall) -> Result<Self::Input, GlorpError> {
			ensure_call_id(Self::ID, &call.id)?;
			decode_required::<crate::StreamTokenInput>(Self::ID, "input", call.input.as_ref())
		}
	}
}

pub fn build_call(id: &str, input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {
	match id {
		"txn" => calls::Txn::build_raw(input),
		"config-set" => calls::ConfigSet::build_raw(input),
		"config-reset" => calls::ConfigReset::build_raw(input),
		"config-patch" => calls::ConfigPatch::build_raw(input),
		"config-reload" => calls::ConfigReload::build_raw(input),
		"config-persist" => calls::ConfigPersist::build_raw(input),
		"document-replace" => calls::DocumentReplace::build_raw(input),
		"editor-motion" => calls::EditorMotion::build_raw(input),
		"editor-mode" => calls::EditorMode::build_raw(input),
		"editor-insert" => calls::EditorInsert::build_raw(input),
		"editor-backspace" => calls::EditorBackspace::build_raw(input),
		"editor-delete-forward" => calls::EditorDeleteForward::build_raw(input),
		"editor-delete-selection" => calls::EditorDeleteSelection::build_raw(input),
		"editor-history" => calls::EditorHistory::build_raw(input),
		"schema" => calls::Schema::build_raw(input),
		"config" => calls::Config::build_raw(input),
		"document-text" => calls::DocumentText::build_raw(input),
		"editor" => calls::Editor::build_raw(input),
		"capabilities" => calls::Capabilities::build_raw(input),
		"session-attach" => calls::SessionAttach::build_raw(input),
		"session-shutdown" => calls::SessionShutdown::build_raw(input),
		"config-validate" => calls::ConfigValidate::build_raw(input),
		"events-subscribe" => calls::EventsSubscribe::build_raw(input),
		"events-next" => calls::EventsNext::build_raw(input),
		"events-unsubscribe" => calls::EventsUnsubscribe::build_raw(input),
		_ => Err(unknown_call(id)),
	}
}

pub fn build_call_result(id: &str, output: &GlorpValue) -> Result<GlorpCallResult, GlorpError> {
	match id {
		"txn" => calls::Txn::respond(calls::Txn::decode_output(output)?),
		"config-set" => calls::ConfigSet::respond(calls::ConfigSet::decode_output(output)?),
		"config-reset" => calls::ConfigReset::respond(calls::ConfigReset::decode_output(output)?),
		"config-patch" => calls::ConfigPatch::respond(calls::ConfigPatch::decode_output(output)?),
		"config-reload" => calls::ConfigReload::respond(calls::ConfigReload::decode_output(output)?),
		"config-persist" => calls::ConfigPersist::respond(calls::ConfigPersist::decode_output(output)?),
		"document-replace" => calls::DocumentReplace::respond(calls::DocumentReplace::decode_output(output)?),
		"editor-motion" => calls::EditorMotion::respond(calls::EditorMotion::decode_output(output)?),
		"editor-mode" => calls::EditorMode::respond(calls::EditorMode::decode_output(output)?),
		"editor-insert" => calls::EditorInsert::respond(calls::EditorInsert::decode_output(output)?),
		"editor-backspace" => calls::EditorBackspace::respond(calls::EditorBackspace::decode_output(output)?),
		"editor-delete-forward" => {
			calls::EditorDeleteForward::respond(calls::EditorDeleteForward::decode_output(output)?)
		}
		"editor-delete-selection" => {
			calls::EditorDeleteSelection::respond(calls::EditorDeleteSelection::decode_output(output)?)
		}
		"editor-history" => calls::EditorHistory::respond(calls::EditorHistory::decode_output(output)?),
		"schema" => calls::Schema::respond(calls::Schema::decode_output(output)?),
		"config" => calls::Config::respond(calls::Config::decode_output(output)?),
		"document-text" => calls::DocumentText::respond(calls::DocumentText::decode_output(output)?),
		"editor" => calls::Editor::respond(calls::Editor::decode_output(output)?),
		"capabilities" => calls::Capabilities::respond(calls::Capabilities::decode_output(output)?),
		"session-attach" => calls::SessionAttach::respond(calls::SessionAttach::decode_output(output)?),
		"session-shutdown" => calls::SessionShutdown::respond(calls::SessionShutdown::decode_output(output)?),
		"config-validate" => calls::ConfigValidate::respond(calls::ConfigValidate::decode_output(output)?),
		"events-subscribe" => calls::EventsSubscribe::respond(calls::EventsSubscribe::decode_output(output)?),
		"events-next" => calls::EventsNext::respond(calls::EventsNext::decode_output(output)?),
		"events-unsubscribe" => calls::EventsUnsubscribe::respond(calls::EventsUnsubscribe::decode_output(output)?),
		_ => Err(unknown_call(id)),
	}
}

pub trait RuntimeCallDispatcher {
	fn txn(
		&mut self, input: <calls::Txn as GlorpCallDescriptor>::Input,
	) -> Result<<calls::Txn as GlorpCallDescriptor>::Output, GlorpError>;
	fn config_set(
		&mut self, input: <calls::ConfigSet as GlorpCallDescriptor>::Input,
	) -> Result<<calls::ConfigSet as GlorpCallDescriptor>::Output, GlorpError>;
	fn config_reset(
		&mut self, input: <calls::ConfigReset as GlorpCallDescriptor>::Input,
	) -> Result<<calls::ConfigReset as GlorpCallDescriptor>::Output, GlorpError>;
	fn config_patch(
		&mut self, input: <calls::ConfigPatch as GlorpCallDescriptor>::Input,
	) -> Result<<calls::ConfigPatch as GlorpCallDescriptor>::Output, GlorpError>;
	fn config_reload(
		&mut self, input: <calls::ConfigReload as GlorpCallDescriptor>::Input,
	) -> Result<<calls::ConfigReload as GlorpCallDescriptor>::Output, GlorpError>;
	fn config_persist(
		&mut self, input: <calls::ConfigPersist as GlorpCallDescriptor>::Input,
	) -> Result<<calls::ConfigPersist as GlorpCallDescriptor>::Output, GlorpError>;
	fn document_replace(
		&mut self, input: <calls::DocumentReplace as GlorpCallDescriptor>::Input,
	) -> Result<<calls::DocumentReplace as GlorpCallDescriptor>::Output, GlorpError>;
	fn editor_motion(
		&mut self, input: <calls::EditorMotion as GlorpCallDescriptor>::Input,
	) -> Result<<calls::EditorMotion as GlorpCallDescriptor>::Output, GlorpError>;
	fn editor_mode(
		&mut self, input: <calls::EditorMode as GlorpCallDescriptor>::Input,
	) -> Result<<calls::EditorMode as GlorpCallDescriptor>::Output, GlorpError>;
	fn editor_insert(
		&mut self, input: <calls::EditorInsert as GlorpCallDescriptor>::Input,
	) -> Result<<calls::EditorInsert as GlorpCallDescriptor>::Output, GlorpError>;
	fn editor_backspace(
		&mut self, input: <calls::EditorBackspace as GlorpCallDescriptor>::Input,
	) -> Result<<calls::EditorBackspace as GlorpCallDescriptor>::Output, GlorpError>;
	fn editor_delete_forward(
		&mut self, input: <calls::EditorDeleteForward as GlorpCallDescriptor>::Input,
	) -> Result<<calls::EditorDeleteForward as GlorpCallDescriptor>::Output, GlorpError>;
	fn editor_delete_selection(
		&mut self, input: <calls::EditorDeleteSelection as GlorpCallDescriptor>::Input,
	) -> Result<<calls::EditorDeleteSelection as GlorpCallDescriptor>::Output, GlorpError>;
	fn editor_history(
		&mut self, input: <calls::EditorHistory as GlorpCallDescriptor>::Input,
	) -> Result<<calls::EditorHistory as GlorpCallDescriptor>::Output, GlorpError>;
	fn schema(
		&mut self, input: <calls::Schema as GlorpCallDescriptor>::Input,
	) -> Result<<calls::Schema as GlorpCallDescriptor>::Output, GlorpError>;
	fn config(
		&mut self, input: <calls::Config as GlorpCallDescriptor>::Input,
	) -> Result<<calls::Config as GlorpCallDescriptor>::Output, GlorpError>;
	fn document_text(
		&mut self, input: <calls::DocumentText as GlorpCallDescriptor>::Input,
	) -> Result<<calls::DocumentText as GlorpCallDescriptor>::Output, GlorpError>;
	fn editor(
		&mut self, input: <calls::Editor as GlorpCallDescriptor>::Input,
	) -> Result<<calls::Editor as GlorpCallDescriptor>::Output, GlorpError>;
	fn capabilities(
		&mut self, input: <calls::Capabilities as GlorpCallDescriptor>::Input,
	) -> Result<<calls::Capabilities as GlorpCallDescriptor>::Output, GlorpError>;
	fn events_subscribe(
		&mut self, input: <calls::EventsSubscribe as GlorpCallDescriptor>::Input,
	) -> Result<<calls::EventsSubscribe as GlorpCallDescriptor>::Output, GlorpError>;
	fn events_next(
		&mut self, input: <calls::EventsNext as GlorpCallDescriptor>::Input,
	) -> Result<<calls::EventsNext as GlorpCallDescriptor>::Output, GlorpError>;
	fn events_unsubscribe(
		&mut self, input: <calls::EventsUnsubscribe as GlorpCallDescriptor>::Input,
	) -> Result<<calls::EventsUnsubscribe as GlorpCallDescriptor>::Output, GlorpError>;
}

pub fn dispatch_runtime_call(
	dispatcher: &mut impl RuntimeCallDispatcher, call: GlorpCall,
) -> Result<GlorpCallResult, GlorpError> {
	match call.id.as_str() {
		"txn" => calls::Txn::respond(dispatcher.txn(calls::Txn::decode_call_input(&call)?)?),
		"config-set" => calls::ConfigSet::respond(dispatcher.config_set(calls::ConfigSet::decode_call_input(&call)?)?),
		"config-reset" => {
			calls::ConfigReset::respond(dispatcher.config_reset(calls::ConfigReset::decode_call_input(&call)?)?)
		}
		"config-patch" => {
			calls::ConfigPatch::respond(dispatcher.config_patch(calls::ConfigPatch::decode_call_input(&call)?)?)
		}
		"config-reload" => {
			calls::ConfigReload::respond(dispatcher.config_reload(calls::ConfigReload::decode_call_input(&call)?)?)
		}
		"config-persist" => {
			calls::ConfigPersist::respond(dispatcher.config_persist(calls::ConfigPersist::decode_call_input(&call)?)?)
		}
		"document-replace" => calls::DocumentReplace::respond(
			dispatcher.document_replace(calls::DocumentReplace::decode_call_input(&call)?)?,
		),
		"editor-motion" => {
			calls::EditorMotion::respond(dispatcher.editor_motion(calls::EditorMotion::decode_call_input(&call)?)?)
		}
		"editor-mode" => {
			calls::EditorMode::respond(dispatcher.editor_mode(calls::EditorMode::decode_call_input(&call)?)?)
		}
		"editor-insert" => {
			calls::EditorInsert::respond(dispatcher.editor_insert(calls::EditorInsert::decode_call_input(&call)?)?)
		}
		"editor-backspace" => calls::EditorBackspace::respond(
			dispatcher.editor_backspace(calls::EditorBackspace::decode_call_input(&call)?)?,
		),
		"editor-delete-forward" => calls::EditorDeleteForward::respond(
			dispatcher.editor_delete_forward(calls::EditorDeleteForward::decode_call_input(&call)?)?,
		),
		"editor-delete-selection" => calls::EditorDeleteSelection::respond(
			dispatcher.editor_delete_selection(calls::EditorDeleteSelection::decode_call_input(&call)?)?,
		),
		"editor-history" => {
			calls::EditorHistory::respond(dispatcher.editor_history(calls::EditorHistory::decode_call_input(&call)?)?)
		}
		"schema" => calls::Schema::respond(dispatcher.schema(calls::Schema::decode_call_input(&call)?)?),
		"config" => calls::Config::respond(dispatcher.config(calls::Config::decode_call_input(&call)?)?),
		"document-text" => {
			calls::DocumentText::respond(dispatcher.document_text(calls::DocumentText::decode_call_input(&call)?)?)
		}
		"editor" => calls::Editor::respond(dispatcher.editor(calls::Editor::decode_call_input(&call)?)?),
		"capabilities" => {
			calls::Capabilities::respond(dispatcher.capabilities(calls::Capabilities::decode_call_input(&call)?)?)
		}
		"session-attach" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Runtime)),
		"session-shutdown" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Runtime)),
		"config-validate" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Runtime)),
		"events-subscribe" => calls::EventsSubscribe::respond(
			dispatcher.events_subscribe(calls::EventsSubscribe::decode_call_input(&call)?)?,
		),
		"events-next" => {
			calls::EventsNext::respond(dispatcher.events_next(calls::EventsNext::decode_call_input(&call)?)?)
		}
		"events-unsubscribe" => calls::EventsUnsubscribe::respond(
			dispatcher.events_unsubscribe(calls::EventsUnsubscribe::decode_call_input(&call)?)?,
		),
		_ => Err(unknown_call(&call.id)),
	}
}

pub trait TransportCallDispatcher {
	fn session_shutdown(
		&mut self, input: <calls::SessionShutdown as GlorpCallDescriptor>::Input,
	) -> Result<<calls::SessionShutdown as GlorpCallDescriptor>::Output, GlorpError>;
}

pub fn dispatch_transport_call(
	dispatcher: &mut impl TransportCallDispatcher, call: GlorpCall,
) -> Result<GlorpCallResult, GlorpError> {
	match call.id.as_str() {
		"txn" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Transport)),
		"config-set" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Transport)),
		"config-reset" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Transport)),
		"config-patch" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Transport)),
		"config-reload" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Transport)),
		"config-persist" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Transport)),
		"document-replace" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Transport)),
		"editor-motion" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Transport)),
		"editor-mode" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Transport)),
		"editor-insert" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Transport)),
		"editor-backspace" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Transport)),
		"editor-delete-forward" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Transport)),
		"editor-delete-selection" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Transport)),
		"editor-history" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Transport)),
		"schema" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Transport)),
		"config" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Transport)),
		"document-text" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Transport)),
		"editor" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Transport)),
		"capabilities" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Transport)),
		"session-attach" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Transport)),
		"session-shutdown" => calls::SessionShutdown::respond(
			dispatcher.session_shutdown(calls::SessionShutdown::decode_call_input(&call)?)?,
		),
		"config-validate" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Transport)),
		"events-subscribe" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Transport)),
		"events-next" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Transport)),
		"events-unsubscribe" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Transport)),
		_ => Err(unknown_call(&call.id)),
	}
}

pub trait ClientCallDispatcher {
	fn session_attach(
		&mut self, input: <calls::SessionAttach as GlorpCallDescriptor>::Input,
	) -> Result<<calls::SessionAttach as GlorpCallDescriptor>::Output, GlorpError>;
	fn config_validate(
		&mut self, input: <calls::ConfigValidate as GlorpCallDescriptor>::Input,
	) -> Result<<calls::ConfigValidate as GlorpCallDescriptor>::Output, GlorpError>;
}

pub fn dispatch_client_call(
	dispatcher: &mut impl ClientCallDispatcher, call: GlorpCall,
) -> Result<GlorpCallResult, GlorpError> {
	match call.id.as_str() {
		"txn" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Client)),
		"config-set" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Client)),
		"config-reset" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Client)),
		"config-patch" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Client)),
		"config-reload" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Client)),
		"config-persist" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Client)),
		"document-replace" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Client)),
		"editor-motion" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Client)),
		"editor-mode" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Client)),
		"editor-insert" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Client)),
		"editor-backspace" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Client)),
		"editor-delete-forward" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Client)),
		"editor-delete-selection" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Client)),
		"editor-history" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Client)),
		"schema" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Client)),
		"config" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Client)),
		"document-text" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Client)),
		"editor" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Client)),
		"capabilities" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Client)),
		"session-attach" => {
			calls::SessionAttach::respond(dispatcher.session_attach(calls::SessionAttach::decode_call_input(&call)?)?)
		}
		"session-shutdown" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Client)),
		"config-validate" => calls::ConfigValidate::respond(
			dispatcher.config_validate(calls::ConfigValidate::decode_call_input(&call)?)?,
		),
		"events-subscribe" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Client)),
		"events-next" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Client)),
		"events-unsubscribe" => Err(route_dispatch_error(&call.id, GlorpCallRoute::Client)),
		_ => Err(unknown_call(&call.id)),
	}
}

pub fn call_specs() -> &'static [GlorpCallSpec] {
	CALL_SPECS.as_slice()
}

pub fn call_spec(id: &str) -> Option<&'static GlorpCallSpec> {
	call_specs().iter().find(|spec| spec.id == id)
}

pub fn call_ids() -> Vec<String> {
	call_specs().iter().map(|call| call.id.clone()).collect()
}

pub(crate) fn register_call_schema_type(registry: &mut crate::TypeRegistry, name: &str) -> bool {
	match name {
		"ConfigAssignment" => {
			registry.register::<crate::ConfigAssignment>();
			true
		}
		"ConfigPatchInput" => {
			registry.register::<crate::ConfigPatchInput>();
			true
		}
		"ConfigPathInput" => {
			registry.register::<crate::ConfigPathInput>();
			true
		}
		"EditorHistoryInput" => {
			registry.register::<crate::EditorHistoryInput>();
			true
		}
		"EditorModeInput" => {
			registry.register::<crate::EditorModeInput>();
			true
		}
		"EditorMotionInput" => {
			registry.register::<crate::EditorMotionInput>();
			true
		}
		"EditorStateView" => {
			registry.register::<crate::EditorStateView>();
			true
		}
		"GlorpCall" => {
			registry.register::<crate::GlorpCall>();
			true
		}
		"GlorpCallResult" => {
			registry.register::<crate::GlorpCallResult>();
			true
		}
		"GlorpCapabilities" => {
			registry.register::<crate::GlorpCapabilities>();
			true
		}
		"GlorpConfig" => {
			registry.register::<crate::GlorpConfig>();
			true
		}
		"GlorpEvent" => {
			registry.register::<crate::GlorpEvent>();
			true
		}
		"GlorpEventStreamView" => {
			registry.register::<crate::GlorpEventStreamView>();
			true
		}
		"GlorpOutcome" => {
			registry.register::<crate::GlorpOutcome>();
			true
		}
		"GlorpSchema" => {
			registry.register::<crate::GlorpSchema>();
			true
		}
		"GlorpSessionView" => {
			registry.register::<crate::GlorpSessionView>();
			true
		}
		"GlorpTxn" => {
			registry.register::<crate::GlorpTxn>();
			true
		}
		"OkView" => {
			registry.register::<crate::OkView>();
			true
		}
		"StreamTokenInput" => {
			registry.register::<crate::StreamTokenInput>();
			true
		}
		"TextInput" => {
			registry.register::<crate::TextInput>();
			true
		}
		"TokenAckView" => {
			registry.register::<crate::TokenAckView>();
			true
		}
		_ => false,
	}
}
