use {
	glorp_api_catalog::{CALLS, CallDefinition, CallKind, CallRoute},
	std::{
		collections::BTreeMap,
		fmt::Write,
		path::{Path, PathBuf},
	},
};

pub fn generated_calls_path() -> PathBuf {
	Path::new(env!("CARGO_MANIFEST_DIR"))
		.join("../api/src/generated_calls.rs")
		.components()
		.as_path()
		.to_path_buf()
}

pub fn render_generated_calls() -> String {
	let mut output = String::new();
	write_prelude(&mut output);
	write_call_specs(&mut output);
	write_descriptor_module(&mut output);
	write_build_call(&mut output);
	write_build_call_result(&mut output);
	write_dispatcher(&mut output, CallRoute::Runtime);
	write_dispatcher(&mut output, CallRoute::Transport);
	write_dispatcher(&mut output, CallRoute::Client);
	write_call_helpers(&mut output);
	write_schema_helper(&mut output);
	output
}

pub fn write_generated_calls() -> std::io::Result<bool> {
	let path = generated_calls_path();
	let contents = render_generated_calls();
	let changed = std::fs::read_to_string(&path).map_or(true, |existing| existing != contents);
	if changed {
		std::fs::write(path, contents)?;
	}
	Ok(changed)
}

fn write_prelude(output: &mut String) {
	output.push_str("// Generated by `cargo run -p glorp_api_codegen`. Do not edit by hand.\n");
	output.push_str("use {super::*, std::sync::LazyLock};\n\n");
}

fn write_call_specs(output: &mut String) {
	output.push_str("static CALL_SPECS: LazyLock<Vec<GlorpCallSpec>> = LazyLock::new(|| {\n");
	output.push_str("\tlet specs = vec![\n");
	for call in CALLS {
		let input = call.input.as_ref().map_or_else(
			|| "None".to_owned(),
			|input| format!("Some(named::<{}>())", input.rust_ty),
		);
		let _ = writeln!(
			output,
			"\t\tGlorpCallSpec {{ id: {:?}.to_owned(), kind: GlorpCallKind::{}, route: GlorpCallRoute::{}, docs: {:?}.to_owned(), input: {input}, output: named::<{}>(), transactional: {} }},",
			call.id,
			kind_ident(call.kind),
			route_ident(call.route),
			call.docs,
			call.output.rust_ty,
			call.transactional,
		);
	}
	output.push_str("\t];\n");
	output.push_str("\tdebug_assert_catalog_invariants(&specs);\n");
	output.push_str("\tspecs\n");
	output.push_str("});\n\n");
}

fn write_descriptor_module(output: &mut String) {
	output.push_str("pub mod calls {\n");
	output.push_str("\tuse super::*;\n\n");
	for call in CALLS {
		let input_ty = call.input.as_ref().map_or("()", |input| input.rust_ty);
		let input_type = call.input.as_ref().map_or_else(
			|| "None".to_owned(),
			|input| format!("Some(named::<{}>())", input.rust_ty),
		);
		let build_body = call.input.as_ref().map_or_else(
			|| {
				"\t\t\tlet _ = input;\n\t\t\tOk(GlorpCall { id: Self::ID.to_owned(), input: None })\n".to_owned()
			},
			|_input| {
				"\t\t\tOk(GlorpCall {\n\t\t\t\tid: Self::ID.to_owned(),\n\t\t\t\tinput: Some(encode_value(Self::ID, \"input\", input)?),\n\t\t\t})\n".to_owned()
			},
		);
		let build_raw_body = call.input.as_ref().map_or_else(
			|| {
				"\t\t\tensure_no_input(Self::ID, input)?;\n\t\t\tOk(GlorpCall { id: Self::ID.to_owned(), input: None })\n".to_owned()
			},
			|input| {
				format!(
					"\t\t\tlet input = decode_required::<{}>(Self::ID, \"input\", input)?;\n\t\t\tOk(GlorpCall {{\n\t\t\t\tid: Self::ID.to_owned(),\n\t\t\t\tinput: Some(encode_value(Self::ID, \"input\", input)?),\n\t\t\t}})\n",
					input.rust_ty
				)
			},
		);
		let decode_body = call.input.as_ref().map_or_else(
			|| "\t\t\tensure_no_input(Self::ID, call.input.as_ref())?;\n\t\t\tOk(())\n".to_owned(),
			|input| {
				format!(
					"\t\t\tdecode_required::<{}>(Self::ID, \"input\", call.input.as_ref())\n",
					input.rust_ty
				)
			},
		);
		let _ = writeln!(
			output,
			"\t#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]\n\tpub struct {};\n\n\timpl GlorpCallDescriptor for {} {{\n\t\ttype Input = {};\n\t\ttype Output = {};\n\n\t\tconst ID: &'static str = {:?};\n\t\tconst DOCS: &'static str = {:?};\n\t\tconst KIND: GlorpCallKind = GlorpCallKind::{};\n\t\tconst ROUTE: GlorpCallRoute = GlorpCallRoute::{};\n\t\tconst TRANSACTIONAL: bool = {};\n\n\t\tfn input_type() -> Option<TypeRef> {{\n\t\t\t{input_type}\n\t\t}}\n\n\t\tfn output_type() -> TypeRef {{\n\t\t\tnamed::<{}>()\n\t\t}}\n\n\t\tfn build(input: Self::Input) -> Result<GlorpCall, GlorpError> {{\n{build_body}\t\t}}\n\n\t\tfn build_raw(input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {{\n{build_raw_body}\t\t}}\n\n\t\tfn decode_call_input(call: &GlorpCall) -> Result<Self::Input, GlorpError> {{\n\t\t\tensure_call_id(Self::ID, &call.id)?;\n{decode_body}\t\t}}\n\t}}\n",
			call.descriptor,
			call.descriptor,
			input_ty,
			call.output.rust_ty,
			call.id,
			call.docs,
			kind_ident(call.kind),
			route_ident(call.route),
			call.transactional,
			call.output.rust_ty,
		);
	}
	output.push_str("}\n\n");
}

fn write_build_call(output: &mut String) {
	output.push_str("pub fn build_call(id: &str, input: Option<&GlorpValue>) -> Result<GlorpCall, GlorpError> {\n");
	output.push_str("\tmatch id {\n");
	for call in CALLS {
		let _ = writeln!(
			output,
			"\t\t{:?} => calls::{}::build_raw(input),",
			call.id, call.descriptor
		);
	}
	output.push_str("\t\t_ => Err(unknown_call(id)),\n");
	output.push_str("\t}\n");
	output.push_str("}\n\n");
}

fn write_build_call_result(output: &mut String) {
	output
		.push_str("pub fn build_call_result(id: &str, output: &GlorpValue) -> Result<GlorpCallResult, GlorpError> {\n");
	output.push_str("\tmatch id {\n");
	for call in CALLS {
		let _ = writeln!(
			output,
			"\t\t{:?} => calls::{}::respond(calls::{}::decode_output(output)?),",
			call.id, call.descriptor, call.descriptor
		);
	}
	output.push_str("\t\t_ => Err(unknown_call(id)),\n");
	output.push_str("\t}\n");
	output.push_str("}\n\n");
}

fn write_dispatcher(output: &mut String, route: CallRoute) {
	let trait_name = match route {
		CallRoute::Runtime => "RuntimeCallDispatcher",
		CallRoute::Transport => "TransportCallDispatcher",
		CallRoute::Client => "ClientCallDispatcher",
	};
	let fn_name = match route {
		CallRoute::Runtime => "dispatch_runtime_call",
		CallRoute::Transport => "dispatch_transport_call",
		CallRoute::Client => "dispatch_client_call",
	};
	let route_ident = route_ident(route);

	let _ = writeln!(output, "pub trait {trait_name} {{");
	for call in CALLS.iter().filter(|call| call.route == route) {
		let input_ty = call.input.as_ref().map_or("()", |input| input.rust_ty);
		let _ = writeln!(
			output,
			"\tfn {}(&mut self, input: <calls::{} as GlorpCallDescriptor>::Input) -> Result<<calls::{} as GlorpCallDescriptor>::Output, GlorpError>;",
			call.handler, call.descriptor, call.descriptor
		);
		let _ = input_ty;
	}
	output.push_str("}\n\n");

	let _ = writeln!(
		output,
		"pub fn {fn_name}(dispatcher: &mut impl {trait_name}, call: GlorpCall) -> Result<GlorpCallResult, GlorpError> {{"
	);
	output.push_str("\tmatch call.id.as_str() {\n");
	for call in CALLS {
		if call.route == route {
			let _ = writeln!(
				output,
				"\t\t{:?} => calls::{}::respond(dispatcher.{}(calls::{}::decode_call_input(&call)?)?),",
				call.id, call.descriptor, call.handler, call.descriptor
			);
		} else {
			let _ = writeln!(
				output,
				"\t\t{:?} => Err(route_dispatch_error(&call.id, GlorpCallRoute::{route_ident})),",
				call.id
			);
		}
	}
	output.push_str("\t\t_ => Err(unknown_call(&call.id)),\n");
	output.push_str("\t}\n");
	output.push_str("}\n\n");
}

fn write_call_helpers(output: &mut String) {
	output.push_str("pub fn call_specs() -> &'static [GlorpCallSpec] {\n\tCALL_SPECS.as_slice()\n}\n\n");
	output.push_str(
		"pub fn call_spec(id: &str) -> Option<&'static GlorpCallSpec> {\n\tcall_specs().iter().find(|spec| spec.id == id)\n}\n\n",
	);
	output.push_str(
		"pub fn call_ids() -> Vec<String> {\n\tcall_specs().iter().map(|call| call.id.clone()).collect()\n}\n\n",
	);
}

fn write_schema_helper(output: &mut String) {
	let mut named_types = BTreeMap::<&str, &str>::from([
		("GlorpCall", "crate::GlorpCall"),
		("GlorpCallResult", "crate::GlorpCallResult"),
		("GlorpTxn", "crate::GlorpTxn"),
	]);
	for call in CALLS {
		register_named_types(&mut named_types, call);
	}

	output.push_str(
		"pub(crate) fn register_call_schema_type(registry: &mut crate::TypeRegistry, name: &str) -> bool {\n\tmatch name {\n",
	);
	for (schema_name, rust_ty) in named_types {
		let _ = writeln!(
			output,
			"\t\t{:?} => {{ registry.register::<{}>(); true }} ,",
			schema_name, rust_ty
		);
	}
	output.push_str("\t\t_ => false,\n\t}\n}\n");
}

fn register_named_types<'a>(named_types: &mut BTreeMap<&'a str, &'a str>, call: &'a CallDefinition) {
	if let Some(input) = call.input {
		for named in input.named_types {
			named_types.insert(named.schema_name, named.rust_ty);
		}
	}
	for named in call.output.named_types {
		named_types.insert(named.schema_name, named.rust_ty);
	}
}

fn kind_ident(kind: CallKind) -> &'static str {
	match kind {
		CallKind::Mutation => "Mutation",
		CallKind::Read => "Read",
		CallKind::Helper => "Helper",
	}
}

fn route_ident(route: CallRoute) -> &'static str {
	match route {
		CallRoute::Runtime => "Runtime",
		CallRoute::Transport => "Transport",
		CallRoute::Client => "Client",
	}
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn checked_in_generated_calls_is_current() {
		let expected = render_generated_calls();
		let actual = std::fs::read_to_string(generated_calls_path()).expect("generated file should be readable");
		assert_eq!(actual, expected);
	}
}
